"""
Django settings for Rahul project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import psycopg2
import socket
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
POSTGRES_URL=os.getenv('POSTGRES_URL')
POSTGRES_URL_NON_POOLING=os.getenv('POSTGRES_URL_NON_POOLING')
POSTGRES_USER=os.getenv('PGUSER')
POSTGRES_HOST=os.getenv('POSTGRES_HOST')
POSTGRES_PASSWORD=os.getenv('PGPASSWORD')
POSTGRES_DATABASE=os.getenv('PGDATABASE')
POSTGRES_URL_NO_SSL=os.getenv('POSTGRES_URL_NO_SSL')
POSTGRES_PRISMA_URL=os.getenv('POSTGRES_PRISMA_URL')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+=$dwy-vf#wx=@y$-w^$%z=dp+z%p^nurm-o_t-rj(*zul2-1@"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['RahulJangra.vercel.app','.vercel.app','192.168.152.13','*','172.20.10.7','192.168.208.13']
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",      # local dev
    "http://localhost:8000",      # local dev
    "https://https://rahul-jangra-leonado10000.vercel.app/",
    "https://my-frontend2.org",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "blog",
    "Portfolio",
    "Anime",
    "myProject",
    "core",
    "CommandCenter",
    "projects",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Rahul.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'Portfolio'), os.path.join(BASE_DIR, 'myProject')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Rahul.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
if socket.gethostname() != 'Leso':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME' : POSTGRES_DATABASE,
            'HOST': POSTGRES_HOST,
            'URL': POSTGRES_URL,
            'PRISMA_URL': POSTGRES_PRISMA_URL,
            'USER': POSTGRES_USER,
            'PASSWORD' : POSTGRES_PASSWORD
        },
    }
else:
    DATABASES = {
        'default': {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "allStaticFiles"
STATICFILES_DIRS = [BASE_DIR, os.path.join(BASE_DIR,'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
