# Generated by Django 4.2.10 on 2025-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bronzelogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("userip", models.CharField(max_length=1000)),
                ("user", models.CharField(max_length=100)),
                ("actionmessage", models.CharField(max_length=1000)),
                ("source", models.CharField(max_length=100)),
            ],
        ),
    ]
