# Generated by Django 4.1.7 on 2026-07-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommandCenter', '0002_alter_bronzelogs_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, unique=True)),
                ('is_auto_flagged', models.BooleanField(default=False)),
                ('auto_flag_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_manual_flagged', models.BooleanField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, help_text='Why did you manually flag this?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SilverLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userip', models.CharField(max_length=100)),
                ('actionmessage', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('bronze_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CommandCenter.bronzelogs')),
                ('ip_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='CommandCenter.flaggedip')),
            ],
        ),
    ]
