# Generated by Django 4.1.7 on 2026-07-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandCenter', '0003_flaggedip_silverlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, unique=True)),
                ('total_visits', models.IntegerField(default=1)),
                ('first_visit', models.DateTimeField()),
                ('last_visit', models.DateTimeField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_auto_flagged', models.BooleanField(default=False)),
                ('auto_flag_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_manual_flagged', models.BooleanField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='silverlogs',
            name='bronze_ref',
        ),
        migrations.RemoveField(
            model_name='silverlogs',
            name='ip_profile',
        ),
        migrations.DeleteModel(
            name='FlaggedIP',
        ),
        migrations.DeleteModel(
            name='SilverLogs',
        ),
    ]
