# Generated by Django 4.1.7 on 2023-11-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_data_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="sender",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="textfield",
            field=models.CharField(max_length=2000),
        ),
    ]
