# Generated by Django 4.2.10 on 2024-10-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_data_image_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image_link",
                    models.CharField(
                        default="https://www.aiscribbles.com/img/variant/large-preview/27293/?v=bf7291",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="data",
            name="image_link",
        ),
    ]
