# Generated by Django 4.2.10 on 2024-10-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_topics_remove_data_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="topic_obj",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.topics",
            ),
        ),
        migrations.AddField(
            model_name="topics",
            name="descrition",
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name="topics",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="topics",
            name="name",
            field=models.CharField(default="shaquille.oatmeal", max_length=100),
        ),
        migrations.AddField(
            model_name="topics",
            name="number_of_messages",
            field=models.IntegerField(default=0),
        ),
    ]
