# Generated by Django 4.2.10 on 2025-06-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ipaddress", models.CharField(max_length=50)),
                ("useragent", models.CharField(max_length=100)),
                ("acceptedlanguage", models.CharField(max_length=50, null=True)),
                ("acceptedencoding", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="visitors",
        ),
    ]
