# Generated by Django 4.2.10 on 2025-06-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0002_visitor_delete_visitors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="useragent",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
