# Generated by Django 4.2.10 on 2025-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0003_alter_visitor_useragent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="acceptedencoding",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="acceptedlanguage",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="useragent",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
