# Generated by Django 4.2.10 on 2025-09-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommandCenter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bronzelogs",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
