# Generated by Django 4.2.10 on 2025-06-25 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField(default=1)),
                ("result", models.CharField(blank=True, max_length=20, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ipaddress", models.CharField(max_length=50)),
                ("useragent", models.CharField(max_length=100)),
                ("acceptedlanguage", models.CharField(max_length=50, null=True)),
                ("acceptedencoding", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rock", models.IntegerField()),
                ("paper", models.IntegerField()),
                ("scissors", models.IntegerField()),
                (
                    "selected_move",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="else.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="else.player"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_as_player1",
                to="else.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_as_player2",
                to="else.player",
            ),
        ),
    ]
