# Generated by Django 4.2.10 on 2025-06-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("else", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visitor",
        ),
    ]
