# Generated by Django 4.2.10 on 2024-10-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_data_sender_alter_data_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
