# Generated by Django 4.2.10 on 2024-10-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_data_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
