# Generated by Django 4.2.10 on 2024-10-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_data_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="image_link",
            field=models.CharField(default="", max_length=200),
        ),
    ]
