# Generated by Django 4.2.10 on 2024-10-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_data_image_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="image_link",
            field=models.CharField(
                default="https://www.aiscribbles.com/img/variant/large-preview/27293/?v=bf7291",
                max_length=200,
            ),
        ),
    ]
