# Generated by Django 4.2.10 on 2024-10-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_data_topic_obj_topics_descrition_topics_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="topic_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.topics"
            ),
        ),
    ]
