# Generated by Django 4.2.10 on 2024-10-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_data_topic_obj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="sender",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
