# Generated by Django 4.2.10 on 2025-06-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_data_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="banned",
            field=models.BooleanField(default=False),
        ),
    ]
