# Generated by Django 4.2.10 on 2024-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myProject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttable",
            name="endDate",
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
